# Holds metadata about the mod https://mwse.github.io/MWSE/guides/metadata/

[package]
name = "Quick Security"
description = "This mod allows you to select lockpicks or probes from a selection menu on trapped or locked doors and containers"
homepage = "https://www.nexusmods.com/morrowind/mods/52918"
repository = "https://github.com/cpassuel/Morrowind-Mods"
authors = ["Thinuviel"]
version = "1.0.0"

# MWSE specific information about this mod
[tools.mwse]
# mod folder don't mix up with mod name
lua-mod = "QuickSecurity"

# adapt to your minimal version of MWSE needed
[dependencies.mwse]
buildnumber = 2907

# in case your mod needs a minimal version of mge-xe
[dependencies.mge-xe]
version = ">=0.10.0"
